on: [push, pull_request,workflow_dispatch]
name: build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test
      run: go test ./internal/... ./cmd/...
      if: runner.os != 'Linux'

    - name: Test with coverage
      run: make test lint build_linux integration_test
      if: runner.os == 'Linux'

    - name: Upload coverage data to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.txt
      if: runner.os == 'Linux'

    - name: Update goreportcard
      uses: creekorful/goreportcard-action@v1.0
      if: runner.os == 'Linux'
